/**
 * Catálogo canónico de códigos de error de red (RF-RED-004).
 * Clasifica cualquier fallo de comunicación, autenticación o configuración
 * con equipos de red (MikroTik RouterOS, OLT ZTE, ONU, etc.) en un código
 * estructurado y auditable.
 */
export enum NetErrorCode {
  NET_DEVICE_OFFLINE = 'NET_DEVICE_OFFLINE',
  NET_TIMEOUT = 'NET_TIMEOUT',
  NET_AUTH_INVALID = 'NET_AUTH_INVALID',
  NET_PORT_UNREACHABLE = 'NET_PORT_UNREACHABLE',
  NET_CONNECTION_REFUSED = 'NET_CONNECTION_REFUSED',
  NET_DNS_RESOLUTION = 'NET_DNS_RESOLUTION',
  NET_NO_ROUTE = 'NET_NO_ROUTE',
  NET_VPN_DOWN = 'NET_VPN_DOWN',
  NET_WG_HANDSHAKE_STALE = 'NET_WG_HANDSHAKE_STALE',
  NET_TLS_ERROR = 'NET_TLS_ERROR',
  NET_PERMISSION_DENIED = 'NET_PERMISSION_DENIED',
  NET_UNSUPPORTED_VERSION = 'NET_UNSUPPORTED_VERSION',
  NET_MISSING_FEATURE = 'NET_MISSING_FEATURE',
  NET_COMMAND_ERROR = 'NET_COMMAND_ERROR',
  NET_TARGET_NOT_FOUND = 'NET_TARGET_NOT_FOUND',
  NET_CONFIG_ERROR = 'NET_CONFIG_ERROR',
  NET_UNKNOWN = 'NET_UNKNOWN',
}
